---
- name: "Example Playbook"
  gather_facts: yes
  hosts: localhost
  connection: local
  tasks:
    - name: "Example Zulip message"
      zulip:
        zuliprc_file_path: "./zuliprc"
        content: "A message from Ansible!"
        notify_users:
          - "john@example.com"
        notify_streams:
          - "Coolest Stream"


